import { Roboto } from "next/font/google";
import "./global.css";
import Navbar from "./Components/common/navbar";
import Footer from "./Components/common/Footer";

const roboto = Roboto({ subsets: ["latin"], weight: ["100", "300", "400", "500", "700", "900"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
